### ISSUE TITLE
Mise à jour API Documentation - Reaction SCENE_SWITCH

### ISSUE THREAD

**Issue by Mitix-EPI** [EasyStreamDev/easystream_main_plugin#34]
Comme nous sommes en pleine évolution des utilisations des scènes, nous avons convenu que nous utiliserons 2 paramètres pour identifier une scène:
* le nom de la scène, important pour l'utilisateur
* son uuid, important pour nous les devs

Actuellement, l'API ne précise pas que la commande `getActReactCouples` renvoie dans les paramètres d'une réaction SCENE_SWITCH à la fois `scene` et `uuid`. C'est aussi le cas pour l'enregistrement d'une nouvelle ActionReaction comme le prouve le screen suivant.
![image](https://github.com/EasyStreamDev/easystream_main_plugin/assets/56727030/26b8f1a4-f3bf-4093-a2d9-f8c58f5cf99a)

Je pense qu'il faudrait penser à l'écrire quelque part pour que les 3 parties (desktop, mobile et API) conviennent d'un format unique et permette l'intéropérabilité des applications.

@YerimB

**Comment by YerimB** [comment]
Ce [commit](https://github.com/EasyStreamDev/easystream_main_plugin/commit/cf8324b240ab48049ffcc22efd17b1c5f2cf7b4a) corrige le problème. Il est pour le moment uniquement sur les branches de développement. Il sera bientôt merge sur le main accompagné d'une release.

- L'identification des scènes se fait désormais par UUID.
- Les requêtes suivantes prennent maintenant en compte l'UUID:
1. [getAllScenes](https://github.com/EasyStreamDev/easystream_main_plugin/blob/devRomain/APIdocumentation.md#getting-all-scenes-basic-data)
2. setActionReaction (voir dans la rubrique [Reactions](https://github.com/EasyStreamDev/easystream_main_plugin/blob/devRomain/APIdocumentation.md#getting-all-scenes-basic-data)). Pour cette requête, comme mentionné sur la documentation, il n'est plus nécessaire de préciser le nom de la scène, l'UUID suffit.
3. getActReactCouples (voir dans la rubrique [Reactions](https://github.com/EasyStreamDev/easystream_main_plugin/blob/devRomain/APIdocumentation.md#getting-all-scenes-basic-data))
