### ISSUE TITLE
[BROADCAST] - Fix API Documentation

### ISSUE THREAD

**Issue by Mitix-EPI** [EasyStreamDev/easystream_main_plugin#35]
Précédemment, nous avons mis en place un certain format d'envoi et de réception pour les `broadcast`.
Nous nous étions mis d'accord que la clé `data` du broadcast, il y avait la clé `type` qui nous permettait de connaître quelle mise à jour nous devons faire au niveau du client.

Or, j'ai remarqué que pour `Areas Updated`, `Compressors Update` et `Subtitles Update` il n'est actuellement pas inscrit le type de ces derniers dans l'API.

![image](https://github.com/EasyStreamDev/easystream_main_plugin/assets/56727030/e1465207-3093-411f-992d-3b01f841c9a0)

**Aussi**, lors de nos précédents tests, nous avons implémenté le Broadcast du compressor au niveau du back et du client. D'après mon code, nous avons mis en place un type pour la mise au jour du compressor. Le type de cette information est `micLevelChanged`. Devrait-on changer ce nom de type ? Ou bien le conserver mais dans tous les cas, il faudrait que tu rajoutes l'identifiant du type dans la clé `type` de `Compressors Update`.

![image](https://github.com/EasyStreamDev/easystream_main_plugin/assets/56727030/24e4267e-48f9-41e5-b968-59c757634404)

Personne concernée: @YerimB

**Comment by YerimB** [comment]
Bien noté, ce sera fix d'ici ce soir.
Je changerai le `type` du broadcast des Compressors Update de `micLevelChanged` à `compressorSettingsChanged`

**Comment by YerimB** [comment]
Fix: les types des broadcasts manquants ont été ajoutés sur la branch [dev](https://github.com/EasyStreamDev/easystream_main_plugin/tree/dev).
Voir [documentation](https://github.com/EasyStreamDev/easystream_main_plugin/blob/dev/APIdocumentation.md)
