### ISSUE TITLE
Command getSubtitlesSettings missing

### ISSUE THREAD

**Issue by Mitix-EPI** [EasyStreamDev/easystream_main_plugin#36]
Nous avons un broadcast pour recevoir toutes les mises à jour des `Subtitles` mais nous n'avons pas pris en compte qu'il faudrait créer une commande `getSubtitlesSettings` que nous exécuterons dès l'entrée du client sur la page des Subtitles pour récupérer toutes les informations (enable, language, et le TextField qui est en cours de développement).

Qu'en pensez-vous ?

Personnes concernées:
@YerimB @Cedani @GuillaumeRobinSoriano

**Comment by Mitix-EPI** [comment]
@Cedani Penses-tu rajouter cette issue dans ton PLD ?

**Comment by Mitix-EPI** [comment]
J'ai remarqué que dans la nouvelle implémentation de `getSubtitlesSettings` dans la branche `dev` il manque certaines informations:
* subtitles enabled ou non
* language des subtitles

Je pense que ces informations devraient être livrées par la commande `getSubtitlesSettings`

Personnes concernées:
* @YerimB 
* @Cedani

**Comment by YerimB** [comment]
Le plugin ne gardant en mémoire que les champs texte sur lesquels les sous titres sont activés, il faut considérer que ceux que retournent la requête ont les sous-titres activés. Les autres ne sont pas mentionnés.

**Comment by Mitix-EPI** [comment]
Okay sur le point subtitles enabled. Mais sur le point des sélections des languages, comment opérer ?

Je propose que pour chaque field, nous pouvons choisir le language. Pour appliquer cela, il faut que dans l'array de `text_fields` de la requête `getSubtitlesSettings`, il y ait la clé "language" pour chaque élément.

Aussi, j'ai remarqué une incohérence du côté Enabling/Disabling subtitles. Qu'est-ce que signifie la clé `uuid` ??
![image](https://github.com/EasyStreamDev/easystream_main_plugin/assets/56727030/ab71d9d7-23d6-42d5-a13d-aa3b5dd7911e)

Je pense qu'il faudrait organiser une prochaine réunion entre @GuillaumeRobinSoriano @YerimB @Cedani et moi même (@Mitix-EPI) pour convenir de comment on devrait re-architecturer les subtitles.

Aussi, la question de sauvegarde des éléments reste encore un peu floue. Dans le sens où, pour l'instant, aucune des deux parties (server / client) enregistre des données en local (mis à part les réaction). Si je ne me trompe pas, il est question que @lapprenti18 implémente une fonctionnalité d'enregistrement de toutes les données depuis le client vers notre "cloud" (serveur Emeryck). Est-ce exact ??

**Comment by YerimB** [comment]
`uuid` Correspond à l'identifiant unique du champ texte auquel fait référence la requête.
Au sujet du langage, pour le moment le choix n'est pas permis à l'utilisateur donc choisir un langage n'est pas pertinent (anglais disponible uniquement).

Pour les sauvegardes, mieux vaut ouvrir une autre issue.
@Mitix-EPI
